src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="blogs")
     */
    private $User;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="datetime_immutable",options={"default": "CURRENT_TIMESTAMP"})
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $type;
    /**
     * @ORM\Column(type="boolean")
     */
    private $isActivated;

    /**
     * @ORM\OneToMany(targetEntity=Member::class, mappedBy="organizationId")
     */
    private $members;

    /**
     * @ORM\OneToMany(targetEntity=Blog::class, mappedBy="User")
     */
    private $blogs;
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
        $this->type = 'user';
        $this->isActivated = false;
        $this->members = new ArrayCollection();
        $this->blogs = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsActivated(): ?bool
    {
        return $this->isActivated;
    }

    public function setIsActivated(bool $isActivated): self
    {
        $this->isActivated = $isActivated;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, Member>
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(Member $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
            $member->setOrganizationId($this);
        }

        return $this;
    }

    public function removeMember(Member $member): self
    {
        if ($this->members->removeElement($member)) {
            // set the owning side to null (unless already changed)
            if ($member->getOrganizationId() === $this) {
                $member->setOrganizationId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Blog>
     */
    public function getBlogs(): Collection
    {
        return $this->blogs;
    }

    public function addBlog(Blog $blog): self
    {
        if (!$this->blogs->contains($blog)) {
            $this->blogs[] = $blog;
            $blog->setUser($this);
        }

        return $this;
    }

    public function removeBlog(Blog $blog): self
    {
        if ($this->blogs->removeElement($blog)) {
            // set the owning side to null (unless already changed)
            if ($blog->getUser() === $this) {
                $blog->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getUsername();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}
                Goals Link - Home
                            
            {% endblock %}
        </title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('assets/css/style-starter.css') }}">
        {% endblock %}

        {% block style %}{% endblock %}

    </head>
    <body>
        {% include "./components/nav.html.twig" %}

		{%include "./components/flash.html.twig"%}
        {% if app.user and app.user.isActivated == false %}
            <div class="alert alert-warning alert-dismissible" role="alert" style="position: fixed; top: 0; left: 0; width: 100%; z-index: 9999;">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        &times;
                </button>
                <div class="alert-message">
                    <strong>
                        Hey 
                        {{ app.user.username }}
                        !
                    </strong>x
                    You need to activate your account. Resend activation link <a href="{{ path('resend_verif') }}">here</a>
                    		  
                </div>
            </div>
        {% endif %}
        {% block body %}{% endblock %}
        {% include "./components/footer.html.twig" %}

        {% block javascripts %}
            <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            <script src="assets/js/jquery-3.3.1.min.js"></script>
            <script src="assets/js/jquery.waypoints.min.js"></script>
            <script src="assets/js/jquery.countup.js"></script>
            <script src="assets/js/owl.carousel.js"></script>
            <script src="assets/js/jquery.magnific-popup.min.js"></script>
            <script src="assets/js/bootstrap.min.js"></script>

            <script>
			$(document).ready(function () {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
		
					fixedContentPos: false,
					fixedBgPos: true,
		
					overflowY: 'auto',
		
					closeBtnInside: true,
					preloader: false,
		
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
				});
		
				$('.popup-with-move-anim').magnificPopup({
					type: 'inline',
		
					fixedContentPos: false,
					fixedBgPos: true,
		
					overflowY: 'auto',
		
					closeBtnInside: true,
					preloader: false,
		
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-slide-bottom'
				});
			});
		</script>

            <script>
			$('.counter').countUp();
		</script>

            <script>
			$(document).ready(function () {
				$('.owl-one').owlCarousel({
					loop: true,
					margin: 0,
					nav: false,
					responsiveClass: true,
					autoplay: false,
					autoplayTimeout: 5000,
					autoplaySpeed: 1000,
					autoplayHoverPause: false,
					responsive: {
						0: {
							items: 1,
							nav: false
						},
						480: {
							items: 1,
							nav: false
						},
						667: {
							items: 1,
							nav: true
						},
						1000: {
							items: 1,
							nav: true
						}
					}
				})
			})
		</script>

            <script>
			$(document).ready(function () {
				$('.owl-testimonial').owlCarousel({
					loop: true,
					margin: 0,
					nav: false,
					responsiveClass: true,
					autoplay: false,
					autoplayTimeout: 5000,
					autoplaySpeed: 1000,
					autoplayHoverPause: false,
					responsive: {
						0: {
							items: 1,
							nav: false
						},
						480: {
							items: 1,
							nav: false
						},
						667: {
							items: 1,
							nav: false
						},
						1000: {
							items: 1,
							nav: false
						}
					}
				})
			})
		</script>

            <script>
		$(function () {
			$('.navbar-toggler').click(function () {
			$('body').toggleClass('noscroll');
			})
		});
		</script>

            <script>
		$(window).on("scroll", function () {
			var scroll = $(window).scrollTop();
		
			if (scroll >= 80) {
			$("#site-header").addClass("nav-fixed");
			} else {
			$("#site-header").removeClass("nav-fixed");
			}
		});
		
		//Main navigation Active Class Add Remove
		$(".navbar-toggler").on("click", function () {
			$("header").toggleClass("active");
		});
		$(document).on("ready", function () {
			if ($(window).width() > 991) {
			$("header").removeClass("active");
			}
			$(window).on("resize", function () {
			if ($(window).width() > 991) {
				$("header").removeClass("active");
			}
			});
		});
		</script>

        {% endblock %}
    </body>
</html>